[sshd]
enabled  = false

[sshd-ddos]
enabled  = false

[alpine-sshd]
enabled  = true
port     = 2222
filter   = alpine-sshd
logpath  = /var/log/sftp/messages
maxretry = 5
findtime = 600
bantime  = 3600
ignoreip = 127.0.0.1/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16

[alpine-sshd-ddos]
enabled  = true
port     = 2222
filter   = alpine-sshd-ddos
logpath  = /var/log/sftp/messages
maxretry = 5
findtime = 600
bantime  = 3600
ignoreip = 127.0.0.1/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16